/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QuizChadRouteImport } from './routes/quiz_.chad'
import { Route as QuizStacyRouteImport } from './routes/quiz_.stacy'
import { Route as ResultCodeRouteImport } from './routes/result.$code'
import { Route as ResultChadCodeRouteImport } from './routes/result.chad.$code'
import { Route as ResultStacyCodeRouteImport } from './routes/result.stacy.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizChadRoute = QuizChadRouteImport.update({
  id: '/quiz_/chad',
  path: '/quiz/chad',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizStacyRoute = QuizStacyRouteImport.update({
  id: '/quiz_/stacy',
  path: '/quiz/stacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultCodeRoute = ResultCodeRouteImport.update({
  id: '/result/$code',
  path: '/result/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultChadCodeRoute = ResultChadCodeRouteImport.update({
  id: '/result/chad/$code',
  path: '/result/chad/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultStacyCodeRoute = ResultStacyCodeRouteImport.update({
  id: '/result/stacy/$code',
  path: '/result/stacy/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/terms': typeof TermsRoute
  '/quiz/chad': typeof QuizChadRoute
  '/quiz/stacy': typeof QuizStacyRoute
  '/result/$code': typeof ResultCodeRoute
  '/result/chad/$code': typeof ResultChadCodeRoute
  '/result/stacy/$code': typeof ResultStacyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/terms': typeof TermsRoute
  '/quiz/chad': typeof QuizChadRoute
  '/quiz/stacy': typeof QuizStacyRoute
  '/result/$code': typeof ResultCodeRoute
  '/result/chad/$code': typeof ResultChadCodeRoute
  '/result/stacy/$code': typeof ResultStacyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/terms': typeof TermsRoute
  '/quiz_/chad': typeof QuizChadRoute
  '/quiz_/stacy': typeof QuizStacyRoute
  '/result/$code': typeof ResultCodeRoute
  '/result/chad/$code': typeof ResultChadCodeRoute
  '/result/stacy/$code': typeof ResultStacyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/credits'
    | '/how-it-works'
    | '/privacy'
    | '/quiz'
    | '/terms'
    | '/quiz/chad'
    | '/quiz/stacy'
    | '/result/$code'
    | '/result/chad/$code'
    | '/result/stacy/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/credits'
    | '/how-it-works'
    | '/privacy'
    | '/quiz'
    | '/terms'
    | '/quiz/chad'
    | '/quiz/stacy'
    | '/result/$code'
    | '/result/chad/$code'
    | '/result/stacy/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/credits'
    | '/how-it-works'
    | '/privacy'
    | '/quiz'
    | '/terms'
    | '/quiz_/chad'
    | '/quiz_/stacy'
    | '/result/$code'
    | '/result/chad/$code'
    | '/result/stacy/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreditsRoute: typeof CreditsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  TermsRoute: typeof TermsRoute
  QuizChadRoute: typeof QuizChadRoute
  QuizStacyRoute: typeof QuizStacyRoute
  ResultCodeRoute: typeof ResultCodeRoute
  ResultChadCodeRoute: typeof ResultChadCodeRoute
  ResultStacyCodeRoute: typeof ResultStacyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz_/chad': {
      id: '/quiz_/chad'
      path: '/quiz/chad'
      fullPath: '/quiz/chad'
      preLoaderRoute: typeof QuizChadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz_/stacy': {
      id: '/quiz_/stacy'
      path: '/quiz/stacy'
      fullPath: '/quiz/stacy'
      preLoaderRoute: typeof QuizStacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$code': {
      id: '/result/$code'
      path: '/result/$code'
      fullPath: '/result/$code'
      preLoaderRoute: typeof ResultCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/chad/$code': {
      id: '/result/chad/$code'
      path: '/result/chad/$code'
      fullPath: '/result/chad/$code'
      preLoaderRoute: typeof ResultChadCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/stacy/$code': {
      id: '/result/stacy/$code'
      path: '/result/stacy/$code'
      fullPath: '/result/stacy/$code'
      preLoaderRoute: typeof ResultStacyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreditsRoute: CreditsRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  TermsRoute: TermsRoute,
  QuizChadRoute: QuizChadRoute,
  QuizStacyRoute: QuizStacyRoute,
  ResultCodeRoute: ResultCodeRoute,
  ResultChadCodeRoute: ResultChadCodeRoute,
  ResultStacyCodeRoute: ResultStacyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
